name: "annict2anilist"

author: "ryohidaka"

description: "Annict から AniList にライブラリを同期する `annict2anilist` を実行するGitHub Actions."

branding:
  color: orange
  icon: tv

inputs:
  annict-client-id:
    description: "AnnictのクライアントID"
    required: true

  annict-client-secret:
    description: "Annictのクライアントシークレット"
    required: true

  anilist-client-id:
    description: "AnilistのクライアントID"
    required: true

  anilist-client-secret:
    description: "Anilistのクライアントシークレット"
    required: true

  anilist-access-token:
    description: "Anilistのアクセストークン"
    required: true

  anilist-refresh-token:
    description: "Anilistのリフレッシュトークン"
    required: true

  annict-access-token:
    description: "Annictのリフレッシュトークン"
    required: true

  dry-run:
    description: "デバッグフラグ (デフォルト: `0`)"
    required: false
    default: 0

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Generate token directory
      run: mkdir -p $GITHUB_ACTION_PATH/token
      shell: bash

    - name: Generate token-anilist.json
      run: |
        $GITHUB_ACTION_PATH/scripts/anilist_token.sh \
          ${{ inputs.anilist-access-token }} \
          ${{ inputs.anilist-refresh-token }}
      shell: bash

    - name: Generate token-annict.json
      run: |
        $GITHUB_ACTION_PATH/scripts/annict_token.sh \
          ${{ inputs.annict-access-token }}
      shell: bash

    - name: Run annict2anilist container
      run: |
        chmod -R 777 $GITHUB_ACTION_PATH/token
        docker compose -f $GITHUB_ACTION_PATH/docker-compose.yml up
      shell: bash
      env:
        ANNICT_CLIENT_ID: ${{ inputs.annict-client-id }}
        ANNICT_CLIENT_SECRET: ${{ inputs.annict-client-secret }}
        ANILIST_CLIENT_ID: ${{ inputs.anilist-client-id }}
        ANILIST_CLIENT_SECRET: ${{ inputs.anilist-client-secret }}
        DRY_RUN: ${{ inputs.dry-run }}
