name: "action-annict2anilist"

author: "ryohidaka"

description: "Annict から AniList にライブラリを同期する `annict2anilist` を実行するGitHub Actions."

branding:
  color: green
  icon: send

inputs:

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Generate token directory
      run: mkdir -p token
      shell: bash
