name: "action-annict2anilist"

author: "ryohidaka"

description: "Annict から AniList にライブラリを同期する `annict2anilist` を実行するGitHub Actions."

branding:
  color: green
  icon: send

inputs:
  anilist-access-token:
    description: "Anilistのアクセストークン"
    required: true

  anilist-refresh-token:
    description: "Anilistのリフレッシュトークン"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Generate token directory
      run: mkdir -p token
      shell: bash

    - name: Generate token-anilist.json
      run: |
        $GITHUB_ACTION_PATH/scripts/anilist_token.sh \
          ${{ inputs.anilist-access-token }} \
          ${{ inputs.anilist-refresh-token }}
      shell: bash
