name: "Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./"
        with:
          anilist-access-token: ${{ secrets.ANILIST_ACCESS_TOKEN }}
          anilist-refresh-token: ${{ secrets.ANILIST_REFRESH_TOKEN }}
          annict-access-token: ${{ secrets.ANNICT_ACCESS_TOKEN }}
